// The TiltTrack logo (concept D): a tilted monoline trophy with a ball popping out of the cup, and the
// "TiltTrack" wordmark — white "Tilt", primary "Track", Inter 900. Every surface that shows the
// brand uses this, so the mark and the casing stay in one place.
//
// The trophy geometry is the same as public/brand/D-icon*.svg (generated by brand/gen.js); the
// wordmark is live text rather than the SVG's outlined paths, so it stays crisp and readable.
// Small sizes use the "small" cut — no motion ticks, thicker strokes — which reads at 20–40px.

type Size = 'xs' | 'header' | 'lg' | 'xl';

const SIZES: Record<Size, { mark: string; text: string; gap: string; glow: number; small: boolean }> = {
  xs: { mark: 'h-5', text: 'text-base', gap: 'gap-1.5', glow: 1.5, small: true },
  header: { mark: 'h-8 md:h-10', text: 'text-[1.35rem] md:text-[1.75rem]', gap: 'gap-2 md:gap-2.5', glow: 2, small: true },
  lg: { mark: 'h-20', text: 'text-3xl', gap: 'gap-4', glow: 3, small: false },
  xl: { mark: 'h-24 sm:h-28', text: 'text-4xl', gap: 'gap-5', glow: 4, small: false },
};

// The trophy in its own coordinates (shared by both cuts).
const TROPHY = [
  'M150,70 H450 V140 C450,258 382,322 300,322 C218,322 150,258 150,140 Z',
  'M150,104 H108 C70,104 58,140 64,170 C74,222 120,248 172,250',
  'M450,104 H492 C530,104 542,140 536,170 C526,222 480,248 428,250',
  'M300,322 V420',
  'M220,470 C220,436 250,420 300,420 C350,420 380,436 380,470',
  'M190,520 H410',
];

function Mark({ small, className, glow, label }: { small: boolean; className: string; glow: number; label?: string }) {
  // viewBoxes are the drawn extent of D-icon(-small).svg in its 1024 canvas, so the mark sits flush.
  const a11y = label ? { role: 'img', 'aria-label': label } : { 'aria-hidden': true as const };
  return (
    <svg
      viewBox={small ? '138 103 713 846' : '193 134 612 774'}
      className={`${className} w-auto flex-none text-primary`}
      style={{ filter: `drop-shadow(0 0 ${glow}px hsl(var(--primary) / 0.6))`, overflow: 'visible' }}
      {...a11y}
    >
      <g transform="rotate(-9 512 512)">
        {small ? (
          <g transform="translate(116 198.5) scale(1.32)">
            <g fill="none" stroke="currentColor" strokeWidth={64} strokeLinecap="round" strokeLinejoin="round">
              {TROPHY.map(d => <path key={d} d={d} />)}
            </g>
            <circle cx={300} cy={-18} r={54} fill="currentColor" />
          </g>
        ) : (
          <g transform="translate(158 249.45) scale(1.18)">
            <g fill="none" stroke="currentColor" strokeWidth={42} strokeLinecap="round" strokeLinejoin="round">
              {TROPHY.map(d => <path key={d} d={d} />)}
            </g>
            <circle cx={300} cy={3} r={44} fill="currentColor" />
            <g stroke="currentColor" strokeWidth={23.1} strokeLinecap="round" opacity={0.9}>
              <path d="M206,12 L232,30" />
              <path d="M394,12 L368,30" />
              <path d="M300,-86 V-64" />
            </g>
          </g>
        )}
      </g>
    </svg>
  );
}

/** "TiltTrack" as live text — the casing is the brand: capital T in each half. */
export function Wordmark({ className = '' }: { className?: string }) {
  return (
    <span className={`font-display font-black tracking-[0.02em] leading-none whitespace-nowrap ${className}`}>
      <span className="text-white">Tilt</span>
      <span className="text-primary [text-shadow:0_0_0.2em_hsl(var(--primary)/0.6)]">Track</span>
    </span>
  );
}

interface BrandLogoProps {
  /** `mark` = the trophy only; `full` = trophy + wordmark. */
  variant?: 'mark' | 'full';
  size?: Size;
  /** `full` only: wordmark beside the trophy, or under it. */
  layout?: 'inline' | 'stacked';
  className?: string;
}

export default function BrandLogo({ variant = 'full', size = 'header', layout = 'inline', className = '' }: BrandLogoProps) {
  const s = SIZES[size];
  if (variant === 'mark') {
    return <Mark small={s.small} className={`${s.mark} ${className}`} glow={s.glow} label="TiltTrack" />;
  }
  return (
    <span className={`inline-flex ${layout === 'stacked' ? 'flex-col' : ''} items-center ${s.gap} ${className}`}>
      <Mark small={s.small} className={s.mark} glow={s.glow} />
      <Wordmark className={s.text} />
    </span>
  );
}
